version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: dmysql
    environment:
      MYSQL_DATABASE: base
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
  
  myadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on: 
      - mysql
    ports: 
      - "82:80"
    links:
      - mysql:db
    restart: always

  web:
    image: miphp
    container_name: dphp
    build: ./dockerfiles/
    ports:
      - "80:80"
    volumes:
      - ./php:/var/www/html
    links:
      - mysql
    restart: always




